### ISSUE TITLE
1.0.13 breaking `change-case` imports

### ISSUE THREAD

**Issue by ardatan** [btxtiger/change-case-all#2]
https://unpkg.com/change-case-all@1.0.12/dist/index.js
 the way of `change-case-all`  importing and exporting `change-case` was working fine but in the latest version 1.0.13 imports `change-case`  function from ` default` while `change-case` doesn't have `default` and this makes all exported functions like `pascalCase` and `camelCase` undefined.
https://unpkg.com/change-case-all@1.0.13/dist/index.js

Related https://github.com/dotansimha/graphql-code-generator/issues/3256#issuecomment-799338073
https://github.com/dotansimha/graphql-code-generator/pull/5711

**Comment by jonaaix** [comment]
@ardatan yes thank you, I just also noticed this error. Unfortunately I could not revert the published package. Please keep on version 1.0.12 until I have some tests implemented shortly. You might need to change `^1.0.12` to `1.0.12` in your `package.json`

**Comment by jonaaix** [comment]
@ardatan Should be fixed with `1.0.14`. Sorry for the trouble.

**Comment by ardatan** [comment]
> You might need to change ^1.0.12 to 1.0.12 in your package.json

@btxtiger That's what we did for now :)

> @ardatan Should be fix with 1.0.14. Sorry for the trouble.

Thank you for quick fix and release! <3
