### ISSUE TITLE
Pascal case returns empty string if _ is passed as input

### ISSUE THREAD

**Issue by danielo515** [btxtiger/change-case-all#3]
As simple as the title says.
If you provide this string `_` to pascal case, it returns an empty string. This affects some packages that depend on this library like on this issue: dotansimha/graphql-code-generator/issues/6040

I think that, in case of the result being an empty string, it should return the original string as it was.

**Comment by jonaaix** [comment]
Are you sure this is an issue of this package?
change-case-all only links to the function of change-case, so I guess the issue is located there, as the tests of change-case-all are passing.

**Comment by danielo515** [comment]
Oh, I thought change-case and change-case-all were just convenience alias. Is this not from the same authors/maintainers?

**Comment by jonaaix** [comment]
@danielo515 unfortunately not. This package just bundles all separate change-case functions as single ES6 module
